In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [8]:
np.array(a)




array(['1', '2', '3', '4', 'hello'], dtype='<U11')

In [10]:
b = [1,2,3.5]
b

[1, 2, 3.5]

In [11]:
np.array(b)

array([1. , 2. , 3.5])

In [12]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [27]:
np.random.rand(10)

array([0.85696677, 0.91135282, 0.20256039, 0.94791311, 0.66945706,
       0.20735724, 0.32700367, 0.74349126, 0.28945386, 0.78031164])

In [30]:
np.random.randn(10)

array([-0.16175839,  1.80239303, -0.03283568, -2.34229635,  1.31192908,
       -1.18238292,  0.03619782, -0.87638455,  2.12379862, -1.36239998])

In [32]:
np.random.randint(10,20,10)

array([14, 19, 17, 10, 16, 17, 16, 15, 10, 17])

In [34]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape


(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int32')

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.min()

1

In [40]:
arr.max()

9

In [41]:
arr.sum()

45

In [42]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [43]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [44]:
arr.mean()

5.0

In [45]:
arr.std()

2.581988897471611

In [46]:
arr.argmax()

8

In [47]:
arr.argmin()

0

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr = arr.reshape(6,5)

In [52]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])